export default [
  "Qual coisa boba consegue melhorar instantaneamente o seu humor?",
  "Qual conhecimento completamente inútil você tem orgulho de saber?",
  "Qual assunto você consegue falar por muito mais tempo do que deveria?",
  "Qual foi a sua obsessão mais aleatória dos últimos tempos?",
  "Se pudesse dominar instantaneamente um hobby, qual escolheria?",
  "Qual coisa todo mundo parece gostar, mas você simplesmente não entende?",
  "Qual comida você defenderia mesmo sabendo que muita gente não gosta?",
  "Qual hábito seu provavelmente pareceria estranho para alguém que morasse com você?",
  "Qual foi a última coisa que você aprendeu e pensou: como eu não sabia disso antes?",
  "Se pudesse eliminar uma pequena inconveniência da vida cotidiana, qual seria?",
  "Qual produto você compraria imediatamente se alguém inventasse?",
  "Se seu mês atual tivesse um título, qual seria?",
  "Qual opinião completamente boba você defenderia com muita convicção?",
  "Qual coisa você achava muito difícil e hoje faz sem pensar?",
  "Qual recomendação você recebeu de alguém e realmente incorporou à sua vida?",
  "Qual cheiro te transporta imediatamente para alguma lembrança?",
  "Qual som você considera estranhamente satisfatório?",
  "Qual comida você gostaria de experimentar pela primeira vez de novo?",
  "Qual foi a fase mais aleatória que você já teve?",
  "Qual coisa você fazia quando criança e gostaria que ainda fosse socialmente aceitável fazer?",
  "Se pudesse transformar qualquer atividade em esporte olímpico, qual escolheria?",
  "Se houvesse um campeonato mundial de alguma habilidade sua, em qual você teria chance?",
  "Qual tarefa simples você consegue complicar muito mais do que deveria?",
  "Qual é o seu talento mais específico e menos útil?",
  "Que coisa você sempre perde dentro da própria casa?",
  "Qual objeto da sua casa provavelmente sobreviveria a você?",
  "Se sua casa tivesse uma personalidade, como ela seria?",
  "Qual seria a pior coisa para ouvir de um piloto logo antes de um avião decolar?",
  "Se extraterrestres chegassem à Terra e você pudesse mostrar apenas uma coisa para explicar a humanidade, o que mostraria?",
  "Qual animal você acha que teria a profissão mais engraçada se tivesse que trabalhar?",
  "Se os seus pensamentos aparecessem como legendas sobre a sua cabeça, em qual situação isso seria mais perigoso?",
  "Se você tivesse que trocar suas mãos por objetos, quais objetos escolheria?",
  "Qual seria o pior nome possível para um restaurante?",
  "Qual profissão você acha que seria muito mais divertida se todo mundo tivesse que trabalhar fantasiado?",
  "Se você fosse um fantasma, qual seria a primeira coisa que faria para assustar alguém?",
  "Se você tivesse um botão que produzisse qualquer coisa uma vez por dia, o que ele produziria?",
  "Qual seria a pior superpotência possível?",
  "Se pudesse conversar durante uma hora com qualquer animal, qual escolheria?",
  "Se seu pet pudesse avaliar você como tutor, qual seria a principal reclamação?",
  "Se os animais tivessem redes sociais, qual espécie seria cancelada primeiro?",
  "Qual objeto cotidiano seria muito mais interessante se tivesse sentimentos?",
  "Se pudesse colocar uma placa de aviso sobre você mesmo, o que ela diria?",
  "Qual regra não escrita da sociedade você acha particularmente estranha?",
  "Qual comportamento humano seria muito difícil explicar para um alienígena?",
  "Que coisa aparentemente simples você ainda não aprendeu a fazer direito?",
  "Qual tecnologia você ainda acha um pouco mágica, mesmo entendendo como funciona?",
  "Qual tecnologia atual você acha que parecerá ridícula daqui a 30 anos?",
  "Qual coisa antiga você gostaria que voltasse a ser comum?",
  "Qual invenção moderna você teria mais dificuldade de abandonar?",
  "Se pudesse ver uma estatística sobre a sua própria vida, qual gostaria de consultar?",
  "Se sua vida tivesse uma tela de estatísticas, qual número provavelmente te surpreenderia?",
  "Se pudesse ver quantas horas da sua vida gastou fazendo uma única coisa, qual teria mais medo de descobrir?",
  "Qual momento aparentemente insignificante acabou ficando marcado na sua memória?",
  "Qual foi uma decisão pequena que acabou mudando bastante a sua vida?",
  "Qual coisa você passou a valorizar mais conforme ficou mais velho?",
  "Qual conselho muito comum você acha que não funciona para você?",
  "Qual habilidade você gostaria que ensinassem na escola?",
  "Qual assunto você gostaria de entender muito melhor?",
  "O que você gostaria de ter começado a fazer mais cedo?",
  "Qual coisa você gostaria de fazer mais vezes, mas sempre acaba deixando para depois?",
  "Qual tradição sua ou da sua família você gostaria de manter para sempre?",
  "Qual costume de outra cultura você gostaria que fosse comum por aqui?",
  "Qual lugar comum do seu cotidiano você acha surpreendentemente bonito?",
  "Qual foi a melhor coincidência que já aconteceu com você?",
  "Qual foi a situação mais improvável em que você encontrou alguém conhecido?",
  "Qual foi a desculpa mais criativa que você já ouviu?",
  "Qual foi a coisa mais inesperada que alguém já te ensinou?",
  "Que elogio você gostaria de receber mais vezes?",
  "Qual característica em outras pessoas você admira bastante?",
  "Qual é uma coisa que você percebe rapidamente quando conhece alguém?",
  "Qual tipo de pessoa costuma te fazer rir facilmente?",
  "Qual amizade começou de uma maneira improvável?",
  "Qual foi a conversa aleatória mais interessante que você já teve com um desconhecido?",
  "Se pudesse fazer uma pergunta e receber uma resposta 100% verdadeira, o que perguntaria?",
  "Se pudesse assistir novamente a um momento da sua vida como espectador, qual seria?",
  "Se pudesse mandar uma mensagem de apenas uma frase para você mesmo no passado, o que escreveria?",
  "Se pudesse receber uma carta sua escrita daqui a 20 anos, qual seria a primeira coisa que gostaria de saber?",
  "Qual coisa do presente você acha que seu eu adolescente acharia muito legal?",
  "Qual coisa do presente você acha que seu eu adolescente acharia decepcionante?",
  "Se sua infância tivesse uma trilha sonora, qual música não poderia faltar?",
  "Qual desenho, jogo ou programa marcou mais a sua infância?",
  "Qual coisa você colecionava ou gostaria de ter colecionado quando criança?",
  "Qual era a sua maior certeza quando criança que depois descobriu estar completamente errada?",
  "Qual era a profissão que você imaginava ter quando criança?",
  "Qual foi a primeira coisa que você comprou com dinheiro ganho por você?",
  "Qual comida da infância ainda tem gosto de nostalgia para você?",
  "Qual brincadeira da infância você toparia jogar hoje?",
  "Se pudesse trazer de volta uma moda, brinquedo ou costume da sua infância, qual seria?",
  "Qual música você sabe cantar muito melhor do que gostaria de admitir?",
  "Qual filme você já assistiu vezes demais?",
  "Qual obra você gostaria de esquecer completamente só para poder conhecê-la novamente?",
  "Qual livro, filme, jogo ou série você gostaria que tivesse continuação?",
  "Qual personagem fictício seria uma péssima pessoa para dividir apartamento?",
  "Qual personagem fictício você acha que seria um ótimo amigo?",
  "Qual universo fictício parece legal de visitar, mas horrível para morar?",
  "Qual vilão fictício você acha que teria potencial para ser uma pessoa legal em outro contexto?",
  "Se pudesse entrar em qualquer jogo durante 24 horas, qual escolheria?",
  "Qual música seria inadequada, mas engraçada, para tocar no seu casamento?",
  "Qual música seria a pior escolha possível para tocar no seu funeral?",
  "Se sua vida tivesse uma música de abertura, qual seria o estilo dela?",
  "Qual artista você gostaria de ver ao vivo mesmo que tivesse que viajar muito para isso?",
  "Qual comida você conseguiria comer várias vezes na mesma semana sem enjoar?",
  "Qual prato você acha melhor no dia seguinte do que recém-feito?",
  "Qual alimento você odiava e passou a gostar?",
  "Qual alimento você gostava e hoje não entende por quê?",
  "Qual comida você gostaria de saber preparar perfeitamente?",
  "Qual prato você prepara melhor do que a maioria das pessoas que conhece?",
  "Se pudesse escolher uma sobremesa para não ter calorias, qual seria?",
  "Se tivesse que comer a mesma coisa no café da manhã pelo próximo ano inteiro, o que escolheria?",
  "Qual combinação de comida parece errada, mas funciona muito bem?",
  "Qual restaurante que não existe você gostaria que existisse perto da sua casa?",
  "Qual lugar você visitou sem grandes expectativas e acabou adorando?",
  "Qual viagem você ainda quer muito fazer?",
  "Qual lugar você gostaria de conhecer apenas pela comida?",
  "Qual lugar você gostaria de visitar em uma época específica do ano?",
  "Você prefere viajar com tudo planejado ou descobrir as coisas na hora?",
  "Qual foi o perrengue de viagem que hoje virou uma boa história?",
  "Qual lugar você gostaria de conhecer antes que mude demais?",
  "Se pudesse passar um mês inteiro em outro país, qual escolheria?",
  "Qual coisa você sempre leva em viagens mesmo sabendo que provavelmente não vai usar?",
  "Se ganhasse uma passagem agora para qualquer lugar, mas tivesse que viajar hoje, para onde iria?",
  "Se pudesse escolher uma cidade, em qualquer lugar do mundo para morar, qual seria?",
  "Qual é a coisa mais louca que já fez e, mesmo assim, faria de novo?",
  "Qual aplicativo tem vergonha de ter instalado no celular?",
  "Qual foi o elogio mais estranho que já recebeu?",
  "Por qual apelido vergonhoso era ou ainda é chamado por sua família?",
  "O que você gostaria de nunca ter descoberto como é feito?",
  "Se você fosse um produto, qual seria o seu slogan?",
  "Qual foi a coisa mais inútil que já comprou, mas não se arrepende?",
  "Qual nome jamais colocaria em um filho ou filha porque remete a alguém irritante?",
  "Quais opções gostaria de ver se pudesse clicar nas pessoas com o botão direito do mouse?",
  "Quais trejeitos ou características dos seus pais espera não ter herdado?",
  "Qual foi a coisa mais legal que já fizeram por você?",
  "Qual é o presente mais estranho que já recebeu?",
  "Se você descobrisse que iria morrer em uma semana, o que você gostaria de fazer?",
  "Se você ganhasse na loteria, qual seria a primeira coisa que faria com o dinheiro?",
  "Qual foi o maior mico que você já pagou?",
  "Se você tivesse 10 minutos para entrar numa loja e comprar o que quiser, qual loja escolheria?",
  "Qual foi a última coisa que você fez pela primeira vez?",
  "Se pudesse escolher qualquer pessoa no mundo, quem convidaria para jantar?",
  "Gostaria de ser famoso? De que forma?",
  "Para você, como seria um dia perfeito?",
  "Por quais aspectos de sua vida você se sente mais agradecido?",
  "Se pudesse mudar algo em como foi educado, o que seria?",
  "Se o dinheiro não fosse um problema, o que você faria com o seu tempo?",
  "Se você pudesse acordar num dia com qualquer nova habilidade ou qualidade, qual seria?",
  "Se tivesse um programa de televisão, do que seria?",
  "Qual foi o momento mais embaraçoso que você passou na vida?",
  "Se você pudesse reviver um dia na sua vida, qual seria?",
  "Se pudesse escolher apenas um lugar para comer durante toda a sua vida, qual seria?",
  "Qual é a primeira lembrança que você tem da sua vida (desde o seu nascimento)?",
  "Qual objeto que você tem hoje e que não quer perder nunca?",
  "Qual a celebridade você gostaria de ser melhor amiga?",
  "Qual a combinação mais estranha de comida que você já comeu?",
  "Se você tivesse três desejos a serem realizados, o que desejaria?",
  "Qual foi o maior problema que um amigo já fez você entrar?",
  "Se você pudesse ouvir um único cantor ou cantora pelo resto da sua vida, qual seria?",
  "Qual foi a situação que aconteceu contigo e você se sentiu muito sortudo?",
  "Qual o nome que você acha mais sexy?",
  "Qual a teoria da conspiração que você realmente acredita?",
  "Se você pudesse ser invisível por um dia, o que faria?",
  "Daqui a 40 anos, do que você acha que as pessoas vão sentir falta dos dias de hoje?",
  "Se os animais pudessem falar, qual você acha que seria o mais mal-educado?",
  "Qual foi o lugar mais estranho que você urinou?",
  "Qual foi a coisa mais estranha que você já viu na casa de uma pessoa?",
  "Se a manteiga não se chamasse manteiga, como você acha que ela se chamaria?",
  "Qual animal pequeno você acha que seria engraçado se fosse do tamanho de um cavalo?",
  "Se você descobrisse que tem um clone seu em outro país, o que faria?",
  "Se você fosse preso sem nenhuma explicação, o que os seus amigos e familiares presumiram que você fez?",
  "Se alguém pedisse para ser seu aprendiz, o que você ensinaria?",
  "Se o seu eu de 5 anos atrás de repente se descobrisse habitando o seu corpo atual, o que o seu eu de cinco anos faria primeiro?",
  "Se você pudesse ser representado por uma comida, qual seria?",
  "Se o seu animal de estimação falasse, qual seria a frase que ele mais repetiria?",
  "Qual celebridade é o seu ou a sua crush?",
  "O que é estranho, mas você acha atraente?",
  "Qual foi a melhor viagem que você já fez?",
  "Qual é a regra de vida que você mais acredita?",
  "O que você acha sobre ter amizade com o ex ou a ex?",
  "O que você gosta de fazer para relaxar?",
  "Uma pessoa que não deixa você falar ou uma pessoa que não te responde: qual tipo te irrita mais?",
  "Quando alguém tem uma notícia boa e outra ruim para contar, qual prefere ouvir primeiro?",
  "Se pudesse viver durante um dia a vida de outra pessoa, quem seria?",
  "O que significa ter sucesso para você?",
  "Qual é a banda ou cantor que sempre recomenda quando alguém pede uma indicação?",
  "Qual tarefa doméstica menos gosta de fazer? E qual mais gosta?",
  "Qual pergunta que ninguém faz, mas que gostaria que fizessem a você?",
  "Três coisas que você quer fazer antes de morrer?",
  "Qual foi o motivo mais bobo pelo qual já brigou com alguém?",
  "O que costuma fazer para melhorar um dia ruim?",
  "Se fosse um super-herói, qual poder gostaria de ter?",
  "Qual é o app que mais usa no celular?",
  "Seria imortal, se pudesse? Por quê?",
  "Em qual série de TV ou streaming gostaria de viver?",
  "Qual foi o momento mais assustador da sua vida?",
  "Qual conselho daria a si mesmo(a) de 10 anos atrás?",
  "Diga três objetos que levaria para uma ilha deserta?",
  "O seu primeiro amor foi correspondido?",
  "Qual mania você tenta, mas não consegue perder?",
  "Qual foi a pior compra que já fez na vida?",
  "Se lembra de quando foi que se sentiu adulto(a) pela primeira vez?",
  "Seja sincero(a): qual idade sente ter?",
  "Qual seria o título do filme sobre a sua vida?",
  "Qual ator/atriz interpretaria você em um filme sobre a sua vida?",
  "Qual música te dá um sentimento de nostalgia?",
  "Qual é o mau hábito que acha mais difícil de abandonar?",
  "O que você mais procrastina para fazer?",
  "O que não faria por dinheiro nenhum?",
  "Do que acredita que sentirá mais saudades daqui a 20 anos?",
  "Qual foi o lugar que você mais gostou de conhecer?",
  "Qual é o traço da sua personalidade que você mais gosta?",
  "Qual é a característica essencial que uma pessoa precisa ter para ser sua amiga?",
  "Qual é a lembrança que guarda com mais carinho da época da escola?",
  "Qual história mais gostava de escutar/ler na infância?",
];
