export default [
  "Se pudesse escolher uma cidade, em qualquer lugar do mundo para morar, qual seria?",
  "Qual é a coisa mais louca que já fez e, mesmo assim, faria de novo?",
  "Qual aplicativo tem vergonha de ter instalado no celular?",
  "Qual foi o elogio mais estranho que já recebeu?",
  "Por qual apelido vergonhoso era ou ainda é chamado por sua família?",
  "O que você gostaria de nunca ter descoberto como é feito?",
  "Se você fosse um produto, qual seria o seu slogan?",
  "Qual foi a coisa mais inútil que já comprou, mas não se arrepende?",
  "Qual nome jamais colocaria em um filho ou filha porque remete a alguém irritante?",
  "Quais opções gostaria de ver se pudesse clicar nas pessoas com o botão direito do mouse?",
  "Quais trejeitos ou características dos seus pais espera não ter herdado?",
  "Qual foi a coisa mais legal que já fizeram por você?",
  "Qual é o presente mais estranho que já recebeu?",
  "Se você descobrisse que iria morrer em uma semana, o que você gostaria de fazer?",
  "Se você ganhasse na loteria, qual seria a primeira coisa que faria com o dinheiro?",
  "Qual foi o maior mico que você já pagou?",
  "Se você tivesse 10 minutos para entrar numa loja e comprar o que quiser, qual loja escolheria?",
  "Qual foi a última coisa que você fez pela primeira vez?",
  "Se pudesse escolher qualquer pessoa no mundo, quem convidaria para jantar?",
  "Gostaria de ser famoso? De que forma?",
  "Para você, como seria um dia perfeito?",
  "Por quais aspectos de sua vida você se sente mais agradecido?",
  "Se pudesse mudar algo em como foi educado, o que seria?",
  "Se o dinheiro não fosse um problema, o que você faria com o seu tempo?",
  "Se você pudesse acordar num dia com qualquer nova habilidade ou qualidade, qual seria?",
  "Se tivesse um programa de televisão, do que seria?",
  "Qual foi o momento mais embaraçoso que você passou na vida?",
  "Se você pudesse reviver um dia na sua vida, qual seria?",
  "Se pudesse escolher apenas um lugar para comer durante toda a sua vida, qual seria?",
  "Qual é a primeira lembrança que você tem da sua vida (desde o seu nascimento)?",
  "Qual objeto que você tem hoje e que não quer perder nunca?",
  "Qual a celebridade você gostaria de ser melhor amiga?",
  "Qual a combinação mais estranha de comida que você já comeu?",
  "Se você tivesse três desejos a serem realizados, o que desejaria?",
  "Qual foi o maior problema que um amigo já fez você entrar?",
  "Se você pudesse ouvir um único cantor ou cantora pelo resto da sua vida, qual seria?",
  "Qual foi a situação que aconteceu contigo e você se sentiu muito sortudo?",
  "Qual o nome que você acha mais sexy?",
  "Qual a teoria da conspiração que você realmente acredita?",
  "Se você pudesse ser invisível por um dia, o que faria?",
  "Daqui a 40 anos, do que você acha que as pessoas vão sentir falta dos dias de hoje?",
  "Se os animais pudessem falar, qual você acha que seria o mais mal-educado?",
  "Qual foi o lugar mais estranho que você urinou?",
  "Qual foi a coisa mais estranha que você já viu na casa de uma pessoa?",
  "Se a manteiga não se chamasse manteiga, como você acha que ela se chamaria?",
  "Qual animal pequeno você acha que seria engraçado se fosse do tamanho de um cavalo?",
  "Se você descobrisse que tem um clone seu em outro país, o que faria?",
  "Se você fosse preso sem nenhuma explicação, o que os seus amigos e familiares presumiram que você fez?",
  "Se alguém pedisse para ser seu aprendiz, o que você ensinaria?",
  "Se o seu eu de 5 anos atrás de repente se descobrisse habitando o seu corpo atual, o que o seu eu de cinco anos faria primeiro?",
  "Se você pudesse ser representado por uma comida, qual seria?",
  "Se o seu animal de estimação falasse, qual seria a frase que ele mais repetiria?",
  "Qual celebridade é o seu ou a sua crush?",
  "O que é estranho, mas você acha atraente?",
  "Qual foi a melhor viagem que você já fez?",
  "Qual é a regra de vida que você mais acredita?",
  "O que você acha sobre ter amizade com o ex ou a ex?",
  "O que você gosta de fazer para relaxar?",
  "Uma pessoa que não deixa você falar ou uma pessoa que não te responde: qual tipo te irrita mais?",
  "Quando alguém tem uma notícia boa e outra ruim para contar, qual prefere ouvir primeiro?",
  "Se pudesse viver durante um dia a vida de outra pessoa, quem seria?",
  "O que significa ter sucesso para você?",
  "Qual é a banda ou cantor que sempre recomenda quando alguém pede uma indicação?",
  "Qual tarefa doméstica menos gosta de fazer? E qual mais gosta?",
  "Qual pergunta que ninguém faz, mas que gostaria que fizessem a você?",
  "Três coisas que você quer fazer antes de morrer?",
  "Qual foi o motivo mais bobo pelo qual já brigou com alguém?",
  "O que costuma fazer para melhorar um dia ruim?",
  "Se fosse um super-herói, qual poder gostaria de ter?",
  "Qual é o app que mais usa no celular?",
  "Seria imortal, se pudesse? Por quê?",
  "Em qual série de TV ou streaming gostaria de viver?",
  "Qual foi o momento mais assustador da sua vida?",
  "Qual conselho daria a si mesmo(a) de 10 anos atrás?",
  "Diga três objetos que levaria para uma ilha deserta?",
  "O seu primeiro amor foi correspondido?",
  "Qual mania você tenta, mas não consegue perder?",
  "Qual foi a pior compra que já fez na vida?",
  "Se lembra de quando foi que se sentiu adulto(a) pela primeira vez?",
  "Seja sincero(a): qual idade sente ter?",
  "Qual seria o título do filme sobre a sua vida?",
  "Qual ator/atriz interpretaria você em um filme sobre a sua vida?",
  "Qual música te dá um sentimento de nostalgia?",
  "Qual é o mau hábito que acha mais difícil de abandonar?",
  "O que você mais procrastina para fazer?",
  "O que não faria por dinheiro nenhum?",
  "Do que acredita que sentirá mais saudades daqui a 20 anos?",
  "Qual foi o lugar que você mais gostou de conhecer?",
  "Qual é o traço da sua personalidade que você mais gosta?",
  "Qual é a característica essencial que uma pessoa precisa ter para ser sua amiga?",
  "Qual é a lembrança que guarda com mais carinho da época da escola?",
  "Qual história mais gostava de escutar/ler na infância?",
];
